"""create stores

Revision ID: 91365ab87ed4
Revises:
Create Date: 2026-05-18 23:17:41.388855

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "91365ab87ed4"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stores",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("area", sa.String(), nullable=False),
        sa.Column("address", sa.String(), nullable=True),
        sa.Column("map_url", sa.String(), nullable=True),
        sa.Column(
            "price_band",
            sa.Enum("LOW", "MIDDLE", "HIGH", name="priceband"),
            nullable=False,
        ),
        sa.Column("styles", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("colors", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_stores_slug"), "stores", ["slug"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_stores_slug"), table_name="stores")
    op.drop_table("stores")
    # ### end Alembic commands ###
